- name: Start scheduler instance
  hosts: localhost
  gather_facts: false
  connection: local
  vars_files:
  - ./vars/external_vars.yml
  vars:
    instance_ids:
      - '{{ airflow_scheduler_instance_id }}'
    region: '{{ airflow_scheduler_aws_region }}'
  tasks:

    - name: Start the instance
      ec2:
        instance_ids: '{{ instance_ids }}'
        region: '{{ region }}'
        state: running
        wait: True
        vpc_subnet_id: '{{ subnet_id }}'
        assign_public_ip: yes

    - name: Gather remote EC2 facts
      ec2_remote_facts:
        region: "{{ region }}"
        filters:
          instance_id: '{{ instance_ids }}'
      register: ec2_facts

    - name: Print out SSH connect public DNS
      debug:
        msg: "ssh -i '{{ pem_file_name }}' ubuntu@{{ item.public_dns_name }}"
      with_items: '{{ ec2_facts.instances }}'
